name: Moving tickets on Trello

on:
  pull_request:
    branches:
      - main

jobs:
  move_to_in_pr_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run node install
        run: npm install

      - name: Printing something
        run: echo WHY
