name: Moving tickets on Trello

on:
  pull_request:
    branches:
      - main
    types: [opened, closed]
  push:
    branches:
      - feat/*
      - fix/*

jobs:
  move_to_in_pr_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run node install
        run: npm install --force

      - name: Run ESLINT
        run: npx eslint . --ext .js,.jsx,.ts,.tsx --config .eslintrc.ci.js

      - name: Set Branch Name Environment Variable
        run: echo "BRANCH_NAME=$( [[ $GITHUB_EVENT_NAME == 'pull_request' ]] && echo ${{ github.head_ref }} || echo ${GITHUB_REF#refs/heads/} )" >> $GITHUB_ENV

      - name: Test NodeJS Script
        env:
          TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
          TRELLO_AUTH_TOKEN: ${{ secrets.TRELLO_AUTH_TOKEN }}
          TRELLO_LIST_IN_PR_REVIEW: ${{ secrets.TRELLO_LIST_IN_PR_REVIEW }}
        run: node scripts/workflows/move_trello_tickets.js

  move_to_test_on_prod:
    needs: move_to_in_pr_review
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run node install
        run: npm install --force

      - name: Set Branch Name Environment Variable
        run: echo "BRANCH_NAME=$( [[ $GITHUB_EVENT_NAME == 'pull_request' ]] && echo ${{ github.head_ref }} || echo ${GITHUB_REF#refs/heads/} )" >> $GITHUB_ENV

      - name: Move ticket to 'TEST ON PROD'
        env:
          TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
          TRELLO_AUTH_TOKEN: ${{ secrets.TRELLO_AUTH_TOKEN }}
          TRELLO_LIST_TEST_ON_PROD: ${{ secrets.TRELLO_LIST_TEST_ON_PROD }}
        run: node scripts/workflows/move_trello_tickets.js merged
